services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: cube-php:8.4.17-fpm-alpine
    container_name: cube-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.ini.production:/usr/local/etc/php/conf.d/custom.ini:ro
      - ./docker/php/www.conf.production:/usr/local/etc/php-fpm.d/www.conf:ro
    networks:
      - cube-network

  nginx:
    image: nginx:1.29.4-alpine
    container_name: cube-nginx
    restart: unless-stopped
    ports:
      - "8002:80"
    volumes:
      - ./src:/var/www/html:ro
      - ./docker/nginx/production.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - cube-network

networks:
  cube-network:
    driver: bridge
